# Generated by Django 4.2.5 on 2023-09-15 04:34

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to=shop.models.GetFileName)),
                ('status', models.BooleanField(default=False, help_text='0-Show | 1-Hidden')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venter', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('Original_price', models.IntegerField()),
                ('shelling_price', models.IntegerField()),
                ('image', models.ImageField(upload_to=shop.models.GetFileName)),
                ('status', models.BooleanField(default=False, help_text='0-Show | 1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-normal | 1-trending')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
